### PR TITLE
feat: extends-ovh

### LINKED ISSUE #329: custom configuration
tried to create a custom config without success :

https://github.com/SocialGouv/template/pull/159/files#diff-95d359a681fb5676ceb5c7e8333dd1c8acff76d102243d07113ff0cc5fb10a92

### PR DESCRIPTION
**Pull request by devthejo**
fix #329

### CODE REVIEW

**Comment by revolunet** [comment]
Looks like the custom storageclass isnt used when no cnpg-cluster.storage kye is defined

**Comment by devthejo** [comment]
> Looks like the custom storageclass isnt used when no cnpg-cluster.storage key is defined

fixed

**Comment by revolunet** [comment]
With this values :
```yml
pg-hasura:
  ~chart: pg

pg-keycloak:
  ~chart: pg
```
and this config :
```yaml
projectName: fabrique

dependencies:
  fabrique:
    extends: ovh

```

i still get `storageClass: managed-csi` while the URLs are correct

**Comment by revolunet** [comment]
would be nice to add some tests here

**Comment by devthejo** [comment]
> would be nice to add some tests here

fixed

**Comment by revolunet** [comment]
awesome, thanks

**Pull request merged**
